config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :events

  get 'signup'  => 'users#new'
  get '/events/invite/:id', to: 'events#invite', as: :event_invite
  post '/events/invite/:id', to: 'events#add', as: :add_invitation
  get '/events/guests/:id', to: 'events#guests', as: :show_guests

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'sessions#new'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  has_many   :event_guests
  has_many   :guests, :through => :event_guests, :source => :user
  validates :user_id, presence: true
  validates :name, presence: true
  validates :description, presence: true

  enum accessibility: ["Public", "Invitation only", "Private"]

  mount_uploader :picture, PictureUploader
end

app/models/event_guest.rb
class EventGuest < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates_uniqueness_of :event_id, :scope => :user_id

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  before_save { self.email = email.downcase }
  MAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: { with: MAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }

  has_many :event_guests, dependent: :destroy
  has_many :events, :through => :event_guests

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  include SessionsHelper


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def regenera_manifest

    require 'tempfile'
    require 'fileutils'


    path = 'public/offline.appcache'
    temp_file = Tempfile.new('offline.appcache')
    begin
      temp_file.write("CACHE MANIFEST\n")
      temp_file.write("# v #{Time.now.to_i}\n")
      f= File.open(path, 'r')
      2.times {f.gets}
      f.each_line do |line|
        temp_file.puts  line
      end
      temp_file.rewind
      FileUtils.mv(temp_file.path, path)
    ensure
      temp_file.close
      temp_file.unlink
    end
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :add, :invite, :guests]
  before_action :force_login, only: [:index, :new, :invite, :show, :edit, :update, :destroy, :add]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def invite
  end

  def uninvite(guest)
    @event.guests.delete(guest)
  end

  def add
    respond_to do |format|

      #esto habria que toquetearlo mas para que mostrara lo de los errores
      if @event.capacity.nil? || @event.guests.count < @event.capacity

        if !User.find_by(email: params[:email]).nil?
          @event.guests << User.find_by(email: params[:email])
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }

        else
          format.html { render :show, notice: 'User couldnt be registered'  }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      else

        format.html { render :show, notice: 'This event capacity is full'  }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end

    end
  end

  def guests

  end


  # POST /events
  # POST /events.json
  def create

    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :description, :accessibility, :capacity, :day, :hour, :picture)
  end

  def force_login
    if !logged_in?
      redirect_to '/login'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if !current_user.nil?
      redirect_to current_user
    end
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'There has been a login error'
      render 'new'
    end
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    if !current_user.nil?
      redirect_to current_user
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: {multipart: true, "data-ajax"=> "false"} do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :accessibility %>
    <%= f.select :accessibility, Event.accessibilities.keys %>
  </div>
  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>
  <div class="field date-select">
    <%= f.label :day %>
    <%= f.date_select :day %>
  </div>
  <div class="field hour-select">
    <%= f.label :hour %>
    <%= f.time_select :hour %>
  </div>
    <div class="field">
      <%= f.label :picture %><br>
      <%= f.file_field :picture %>
     <%= f.hidden_field :picture_cache %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/guests.html.erb
<% provide(:titulo, "Events guests") %>

<p id="notice"><%= notice %></p>

<h1>Listing Guests</h1>

<div class="ui-body ui-body-a ui-corner-all">
<table data-role="table" class="ui-responsive">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>


  <% @event.guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.email %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Invite', event_invite_path(@event), class: "ui-btn" %>
</div>

app/views/events/index.html.erb
<% provide(:titulo, "Events") %>

<p id="notice"><%= notice %></p>


<div class="ui-body ui-body-a ui-corner-all">

      <div id="events"></div>


</div>

app/views/events/invite.html.erb
<% provide(:titulo, "Invite guests") %>

<div class="ui-body ui-body-a ui-corner-all">


<%= form_tag({controller: "events", action: "add"}, method: "post") do %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

        <b><%= label_tag(:email, "Write user's email:") %></b>
        <%= text_field_tag(:email) %>
        <%= submit_tag("Add") %>


<% end %>
</div>

app/views/events/new.html.erb
<% provide(:titulo, "New Event") %>
<div class="ui-body ui-body-a ui-corner-all">

<%= render 'form' %>
</div>

app/views/events/show.html.erb
<% provide(:titulo, "Events") %>

<p id="notice"><%= notice %></p>

<div class="ui-body ui-body-a ui-corner-all eventid">


  <h1 id="name-<%= @event.id %>"></h1>

  <% if @event.user_id == current_user.id %>
      <div class="ui-grid-a buttons">
        <div class="ui-block-a">
          <%= link_to "Edit", edit_event_path(@event), "data-role" => "button",
                      class: "ui-btn-corner-all ui-btn ui-icon-edit ui-btn-icon-notext ui-shadow" %>

        </div>
        <div class="ui-block-b">
          <%= link_to 'Destroy', @event, "data-role" => "button",
                      class: "ui-btn-corner-all ui-btn ui-icon-delete ui-btn-icon-notext ui-shadow",
                      method: :delete, data: { confirm: 'Are you sure you want to delete this event?' } %>

        </div>
      </div>

  <% end %>

  <div id="event-<%= @event.id %>"></div>

  <%= link_to 'Invite?', event_invite_path(@event), class: "ui-btn ui-corner-all" %>
  <%= link_to 'Guests', show_guests_path(@event), class: "ui-btn ui-corner-all" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html manifest="/offline.appcache">
<head>
  <title>FaceToFace</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink="true">


<div data-role="page" data-theme="b">
  <div data-role="header" role="banner" data-position="inline" class="ui-header ui-bar-a">
    <h1><%= yield :titulo %></h1>
  </div>
  <div class="ui-content" role="main">
    <%= yield %>
  </div>

  <div data-role="footer" data-position="fixed">
    <div data-role="navbar">
      <ul>
        <li> <%= link_to 'My events', events_path, class: "ui-btn ui-btn-icon-top ui-icon-search ui-btn-active", data: {ajax: "false"} %> </li>

        <li> <%= link_to 'Create', new_event_path, class: "ui-btn-icon-top ui-icon-grid ui-btn-active", data: {ajax: "false"} %> </li>

      </ul>
    </div>
  </div>

</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <p>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <p>
    <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
    </div>
    <p>
      <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
      </div>
    <p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:titulo, "Editing User") %>

<div class="ui-body ui-body-a ui-corner-all">
<%= render 'form' %>

<%= link_to 'Cancel', @user, class: "ui-btn ui-corner-all"%>
</div>

app/views/users/index.html.erb
<% provide(:titulo, "Listing Users") %>

<p id="notice"><%= notice %></p>



<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= content_for :titulo, "Sign Up" %>

<h1>Sign Up</h1>

<%= render 'form' %>
<%= link_to 'Already have an account?', "login", class: "ui-btn ui-corner-all" %>

app/views/users/show.html.erb
<% provide(:titulo, "User Profile") %>

<p id="notice"><%= notice %></p>

<div class="ui-body ui-body-a ui-corner-all">
  <h3>Name:
  <%= @user.name %></h3>

  <h3>Email:
  <%= @user.email %></h3>

<%= link_to 'Edit', edit_user_path(@user), class: "ui-btn ui-corner-all" %>

</div>